// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShopBanQuanAoOnline.Data;

#nullable disable

namespace ShopBanQuanAoOnline.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShopBanQuanAoOnline.Models.Chucvu", b =>
                {
                    b.Property<int>("MaCv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaCV");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCv"));

                    b.Property<double?>("HeSo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(1.0);

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaCv")
                        .HasName("PK__CHUCVU__27258E76F0AD16BB");

                    b.ToTable("CHUCVU");
                });

            modelBuilder.Entity("ShopBanQuanAoOnline.Models.Cthoadon", b =>
                {
                    b.Property<int>("MaCthd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaCTHD");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCthd"));

                    b.Property<int?>("DonGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("MaHd")
                        .HasColumnType("int")
                        .HasColumnName("MaHD");

                    b.Property<int>("MaMh")
                        .HasColumnType("int")
                        .HasColumnName("MaMH");

                    b.Property<short?>("SoLuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1);

                    b.Property<int?>("ThanhTien")
                        .HasColumnType("int");

                    b.HasKey("MaCthd")
                        .HasName("PK__CTHOADON__1E4FA77114E6547F");

                    b.HasIndex("MaHd");

                    b.HasIndex("MaMh");

                    b.ToTable("CTHOADON");
                });

            modelBuilder.Entity("ShopBanQuanAoOnline.Models.Cuahang", b =>
                {
                    b.Property<int>("MaCh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaCH");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCh"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DienThoai")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaCh")
                        .HasName("PK__CUAHANG__27258E005B650D99");

                    b.ToTable("CUAHANG");
                });

            modelBuilder.Entity("ShopBanQuanAoOnline.Models.Danhmuc", b =>
                {
                    b.Property<int>("MaDm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaDM");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDm"));

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaDm")
                        .HasName("PK__DANHMUC__2725866E268E560D");

                    b.ToTable("DANHMUC");
                });

            modelBuilder.Entity("ShopBanQuanAoOnline.Models.Diachi", b =>
                {
                    b.Property<int>("MaDc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaDC");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDc"));

                    b.Property<string>("DiaChi1")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("DiaChi");

                    b.Property<int>("MaKh")
                        .HasColumnType("int")
                        .HasColumnName("MaKH");

                    b.Property<int?>("MacDinh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("PhuongXa")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Đông Xuyên");

                    b.Property<string>("QuanHuyen")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("TP. Long Xuyên");

                    b.Property<string>("TinhThanh")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("An Giang");

                    b.HasKey("MaDc")
                        .HasName("PK__DIACHI__27258664870A5320");

                    b.HasIndex("MaKh");

                    b.ToTable("DIACHI");
                });

            modelBuilder.Entity("ShopBanQuanAoOnline.Models.Hoadon", b =>
                {
                    b.Property<int>("MaHd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaHD");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHd"));

                    b.Property<int>("MaKh")
                        .HasColumnType("int")
                        .HasColumnName("MaKH");

                    b.Property<DateTime?>("Ngay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("TongTien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("MaHd")
                        .HasName("PK__HOADON__2725A6E087B5138C");

                    b.HasIndex("MaKh");

                    b.ToTable("HOADON");
                });

            modelBuilder.Entity("ShopBanQuanAoOnline.Models.Khachhang", b =>
                {
                    b.Property<int>("MaKh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaKH");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKh"));

                    b.Property<string>("DienThoai")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MatKhau")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaKh")
                        .HasName("PK__KHACHHAN__2725CF1E5B5D9BAF");

                    b.ToTable("KHACHHANG");
                });

            modelBuilder.Entity("ShopBanQuanAoOnline.Models.KhuyenMai", b =>
                {
                    b.Property<int>("KhuyenMaiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KhuyenMaiId"));

                    b.Property<decimal?>("GiaTri")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("HinhThuc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly>("NgayBatDau")
                        .HasColumnType("date");

                    b.Property<DateOnly>("NgayKetThuc")
                        .HasColumnType("date");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("TenKhuyenMai")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool?>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("KhuyenMaiId")
                        .HasName("PK__KhuyenMa__820D7497AA6FE558");

                    b.ToTable("KhuyenMai");
                });

            modelBuilder.Entity("ShopBanQuanAoOnline.Models.Mathang", b =>
                {
                    b.Property<int>("MaMh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaMH");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaMh"));

                    b.Property<int?>("GiaBan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("GiaGoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("LuotMua")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("LuotXem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("MaDm")
                        .HasColumnType("int")
                        .HasColumnName("MaDM");

                    b.Property<string>("MoTa")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<short?>("SoLuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0);

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaMh")
                        .HasName("PK__MATHANG__2725DFD90206DBFA");

                    b.HasIndex("MaDm");

                    b.ToTable("MATHANG");
                });

            modelBuilder.Entity("ShopBanQuanAoOnline.Models.Nhanvien", b =>
                {
                    b.Property<int>("MaNv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaNV");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNv"));

                    b.Property<string>("DienThoai")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("MaCv")
                        .HasColumnType("int")
                        .HasColumnName("MaCV");

                    b.Property<string>("MatKhau")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaNv")
                        .HasName("PK__NHANVIEN__2725D70ACB7E38AF");

                    b.HasIndex("MaCv");

                    b.ToTable("NHANVIEN");
                });

            modelBuilder.Entity("ShopBanQuanAoOnline.Models.SuKien", b =>
                {
                    b.Property<int>("SuKienId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SuKienId"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("NgayBatDau")
                        .HasColumnType("date");

                    b.Property<DateOnly>("NgayKetThuc")
                        .HasColumnType("date");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("TenSuKien")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool?>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("SuKienId")
                        .HasName("PK__SuKien__3B964718EB5C0413");

                    b.ToTable("SuKien");
                });

            modelBuilder.Entity("ShopBanQuanAoOnline.Models.Cthoadon", b =>
                {
                    b.HasOne("ShopBanQuanAoOnline.Models.Hoadon", "MaHdNavigation")
                        .WithMany("Cthoadons")
                        .HasForeignKey("MaHd")
                        .IsRequired()
                        .HasConstraintName("FK__CTHOADON__MaHD__5EBF139D");

                    b.HasOne("ShopBanQuanAoOnline.Models.Mathang", "MaMhNavigation")
                        .WithMany("Cthoadons")
                        .HasForeignKey("MaMh")
                        .IsRequired()
                        .HasConstraintName("FK__CTHOADON__MaMH__5FB337D6");

                    b.Navigation("MaHdNavigation");

                    b.Navigation("MaMhNavigation");
                });

            modelBuilder.Entity("ShopBanQuanAoOnline.Models.Diachi", b =>
                {
                    b.HasOne("ShopBanQuanAoOnline.Models.Khachhang", "MaKhNavigation")
                        .WithMany("Diachis")
                        .HasForeignKey("MaKh")
                        .IsRequired()
                        .HasConstraintName("FK__DIACHI__MaKH__52593CB8");

                    b.Navigation("MaKhNavigation");
                });

            modelBuilder.Entity("ShopBanQuanAoOnline.Models.Hoadon", b =>
                {
                    b.HasOne("ShopBanQuanAoOnline.Models.Khachhang", "MaKhNavigation")
                        .WithMany("Hoadons")
                        .HasForeignKey("MaKh")
                        .IsRequired()
                        .HasConstraintName("FK__HOADON__MaKH__5AEE82B9");

                    b.Navigation("MaKhNavigation");
                });

            modelBuilder.Entity("ShopBanQuanAoOnline.Models.Mathang", b =>
                {
                    b.HasOne("ShopBanQuanAoOnline.Models.Danhmuc", "MaDmNavigation")
                        .WithMany("Mathangs")
                        .HasForeignKey("MaDm")
                        .IsRequired()
                        .HasConstraintName("FK__MATHANG__MaDM__45F365D3");

                    b.Navigation("MaDmNavigation");
                });

            modelBuilder.Entity("ShopBanQuanAoOnline.Models.Nhanvien", b =>
                {
                    b.HasOne("ShopBanQuanAoOnline.Models.Chucvu", "MaCvNavigation")
                        .WithMany("Nhanviens")
                        .HasForeignKey("MaCv")
                        .IsRequired()
                        .HasConstraintName("FK__NHANVIEN__MaCV__4D94879B");

                    b.Navigation("MaCvNavigation");
                });

            modelBuilder.Entity("ShopBanQuanAoOnline.Models.Chucvu", b =>
                {
                    b.Navigation("Nhanviens");
                });

            modelBuilder.Entity("ShopBanQuanAoOnline.Models.Danhmuc", b =>
                {
                    b.Navigation("Mathangs");
                });

            modelBuilder.Entity("ShopBanQuanAoOnline.Models.Hoadon", b =>
                {
                    b.Navigation("Cthoadons");
                });

            modelBuilder.Entity("ShopBanQuanAoOnline.Models.Khachhang", b =>
                {
                    b.Navigation("Diachis");

                    b.Navigation("Hoadons");
                });

            modelBuilder.Entity("ShopBanQuanAoOnline.Models.Mathang", b =>
                {
                    b.Navigation("Cthoadons");
                });
#pragma warning restore 612, 618
        }
    }
}
